- /interface/bridge
- /interface/list
- /interface/vlan
- /interface/vxlan
- /interface/vxlan/vteps
- /interface/list/member
- /interface/bridge/port
- /interface/bridge/vlan
- /ip/address
- /ipv6/address
- /ip/pool
- /ipv6/pool
- /ip/dhcp-server
- /ip/dhcp-server/network
- /ipv6/dhcp-server
- /interface/wireguard
- /interface/wireguard/peers
- /system/scheduler
- /routing/filter/rule
- /routing/bgp/connection
- /ip/dhcp-server/lease
- /routing/table
- /routing/rule
- /ip/route
- /user-manager/user
- /user-manager/router
- /tool/netwatch