/ipv6/firewall/filter:

#-------------------------------------icmp
#DENY

- comment: "input_internal_icmpv6_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_PRIVATE
  protocol: icmpv6
  log: 'true'
  log_prefix: 'FW=in_reject T=icmp S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'

- comment: "forward_internal_icmpv6_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_PRIVATE
  protocol: icmpv6
  log: 'true'
  log_prefix: 'FW=fw_reject T=icmp S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'

- comment: "input_public_icmpv6_deny"
  order: bot
  chain: input
  protocol: icmpv6
  log: 'true'
  log_prefix: 'FW=in_reject T=icmp S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop'

- comment: "forward_public_icmpv6_deny"
  order: bot
  chain: forward
  protocol: icmpv6
  log: 'true'
  log_prefix: 'FW=fw_reject T=icmp S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop' 


#-------------------------------------ssh

- comment: "inputv6_internal_ssh_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_PRIVATE
  dst_port: '22'
  protocol: tcp
  log: 'true'
  log_prefix: 'FW=in_reject T=SSH S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'

- comment: "forwardv6_internal_ssh_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_PRIVATE
  dst_port: '22'
  protocol: tcp
  log: 'true'
  log_prefix: 'FW=fw_reject T=SSH S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'


- comment: "intputv6_public_ssh_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_INTERNET
  dst_port: '22'
  protocol: tcp
  log: 'true'
  log_prefix: 'FW=in_drop T=SSH S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop'


- comment: "forwardv6_public_ssh_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_INTERNET
  dst_port: '22'
  protocol: tcp
  log: 'true'
  log_prefix: 'FW=fw_drop T=SSH S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop'



#-------------------------------------nolog drop


#NO LOG SPECIFIC

- comment: "inputv6_src_nolog_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_NOLOG
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'drop'

- comment: "forwardv6_src_nolog_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_NOLOG
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'drop'

- comment: "inputv6_dst_nolog_deny"
  order: bot
  chain: input
  dst_address_list: SET_NET6_NOLOG
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'drop'

- comment: "forwardv6_dst_nolog_deny"
  order: bot
  chain: forward
  dst_address_list: SET_NET6_NOLOG
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'drop'


#NO LOG INVALID

- comment: "intputv6_invalid_public_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_INTERNET
  log: 'false'
  log_prefix: 'no'
  connection_state: 'invalid'
  disabled: 'false'
  action: 'drop'


- comment: "forwardv6_invalid_public_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_INTERNET
  log: 'false'
  log_prefix: 'no'
  connection_state: 'invalid'
  disabled: 'false'
  action: 'drop'

#-------------------------------------GROBAL DROP


- comment: "inputv6_internal_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_PRIVATE
  log: 'true'
  log_prefix: 'FW=in_reject S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'

- comment: "forwardv6_internal_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_PRIVATE
  log: 'true'
  log_prefix: 'FW=fw_reject S=PRIV IPV=6 '
  disabled: 'false'
  action: 'reject'
  reject_with: 'icmp-admin-prohibited'

#    public
- comment: "intputv6_public_deny"
  order: bot
  chain: input
  src_address_list: SET_NET6_INTERNET
  log: 'true'
  log_prefix: 'FW=in_drop S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop'


- comment: "forwardv6_public_deny"
  order: bot
  chain: forward
  src_address_list: SET_NET6_INTERNET
  log: 'true'
  log_prefix: 'FW=fw_drop S=PUB IPV=6 '
  disabled: 'false'
  action: 'drop'