/ipv6/firewall/filter:

# -------------------------------------------------
# The following configuration is just an example.
# You need to create the files for your needs.
# -------------------------------------------------

- comment: "INPUT stablished v6"
  order: posi
  posi: '5'
  chain: input
  connection_state: 'established,related,untracked'
  action: 'accept'

- comment: "FORWARD stablished v6"
  order: posi
  posi: '6'
  chain: forward
  connection_state: 'established,related,untracked'
  action: 'accept'

  