/ip/firewall/filter:
- comment: "local_mgmt"
  order: top
  chain: input
  src_address_list: SET_HOSTS4_ALLOW_MGMT
  dst_port: '21,22,23,80,443,8291,8728,8729,2000'
  protocol: tcp
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'accept'

- comment: "local_mgmt_udp"
  order: top
  chain: input
  src_address_list: SET_HOSTS4_ALLOW_MGMT
  dst_port: '161,1812,1813,5678'
  protocol: udp
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'accept'

- comment: "vpnmgmt_allow_all"
  order: top
  chain: input
  src_address_list: SET_HOSTS4_MGMTVPN
  dst_address_list: SET_HOSTS4_MGMTVPN
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'accept'

- comment: "input_monitoring"
  order: top
  chain: input
  src_address_list: SET_HOSTS4_MONITORING
  dst_port: '161'
  protocol: udp
  log: 'false'
  log_prefix: 'no'
  disabled: 'false'
  action: 'accept'
